name: KickOff
run-name: ${{ github.run_number }} pushed 
on: [push]
jobs:
  run-kickoff-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup JDK-17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Maven Build
      run: |
        mvn -B package --file=pom.xml clean compile 
